baseURL = 'https://gruozachary.github.io/blog/'
languageCode = 'en-us'
title = 'Blog of Thomas Zachary'
theme = 'paper'

[params]
  math = true

  [params.author]
    name = 'Thomas Zachary'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
